export const PROACTIVE_CHECKIN_MAX_PER_WEEK = 3;
export const PROACTIVE_CHECKIN_MIN_SILENCE_HOURS = 24;
export const PROACTIVE_CHECKIN_RECENT_ACTIVITY_HOURS = 6;
export const PROACTIVE_CHECKIN_CARE_SILENCE_MAX_HOURS = 96;
export const PROACTIVE_CHECKIN_CURIOUS_COOLDOWN_DAYS = 7;
export const PROACTIVE_CHECKIN_PAUSE_DAYS = 7;

export const PROACTIVE_MODE_PRIORITY = {
  care: 100,
  useful: 60,
  curious: 30
} as const;
