export const DEFAULT_USER_MIND_LOOKBACK_DAYS = 7;
export const DEFAULT_USER_MIND_ACTIVITY_LOOKBACK_DAYS = 14;
export const DEFAULT_USER_MIND_CONVERSATION_SAMPLE = 24;
export const DEFAULT_USER_MIND_BATCH_SIZE = 25;
