export const WEEKLY_FEEDBACK_COOLDOWN_DAYS = 28;
export const WEEKLY_FEEDBACK_PERIODIC_WEEKS = 6;
export const WEEKLY_FEEDBACK_MOMENTUM_DROP = 15;
export const WEEKLY_FEEDBACK_RESPONSE_WINDOW_DAYS = 5;
export const WEEKLY_FEEDBACK_MIN_MESSAGES_FOR_CONTEXT = 3;
