ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS quiet_hours_enabled BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS quiet_hours_start_hour SMALLINT NOT NULL DEFAULT 22,
ADD COLUMN IF NOT EXISTS quiet_hours_end_hour SMALLINT NOT NULL DEFAULT 7;
